test 7

diff --git a/.github/workflows/build-mac0S-arm64.yml b/.github/workflows/build-mac0S-arm64.yml
--- a/.github/workflows/build-mac0S-arm64.yml
+++ b/.github/workflows/build-mac0S-arm64.yml
@@ -40,12 +40,12 @@ jobs:
 #          version=$(sed -n 's/.*<${PROPS_VERSION_VAR_NAME}>\([^<]*\)<\/${PROPS_VERSION_VAR_NAME}>.*/\1/p' ./src/Directory.Build.props)
 #          echo "PropsVersion=${version}" >> $GITHUB_ENV
 
-      - name: Compare tag with NuGet package version
-        run: |
-          if [ "${{ env.PropsVersion }}" != "${{ env.VERSION }}" ]; then
-            echo "Error: Tag does not match NuGet package version"
-            exit 1
-          fi
+#      - name: Compare tag with NuGet package version
+#        run: |
+#          if [ "${{ env.PropsVersion }}" != "${{ env.VERSION }}" ]; then
+#            echo "Error: Tag does not match NuGet package version"
+#            exit 1
+#          fi
           
       - name: Read version from Info.plist
         id: read-info-version
