test 5

diff --git a/.github/workflows/build-mac0S-arm64.yml b/.github/workflows/build-mac0S-arm64.yml
--- a/.github/workflows/build-mac0S-arm64.yml
+++ b/.github/workflows/build-mac0S-arm64.yml
@@ -29,20 +29,36 @@ jobs:
       - name: Add NuGet source
         run: dotnet nuget add source ${{ env.GITHUB_PACKAGES_URL }} \--username '${{secrets.USER_NAME}}' \--password '${{secrets.GIHUB_NUGET_AUTH_TOKEN}}' \--store-password-in-clear-text
       
-#      - name: Install dependencies
-#        run: |
-#          dotnet restore -r osx-arm64 ./src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj
-#          dotnet restore -r osx-arm64 ./src/${{ env.PROJECT_NAME_DESKTOP }}/${{ env.PROJECT_NAME_DESKTOP }}.csproj
-#
-#      - name: Build
-#        run: |
-#          dotnet build ./src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj --configuration Release --no-restore
-#          dotnet build ./src/${{ env.PROJECT_NAME_DESKTOP }}/${{ env.PROJECT_NAME_DESKTOP }}.csproj --configuration Release --no-restore
-
       - name: Set version variable
         env:
           TAG: ${{ github.ref_name }}
         run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
+        
+      - name: Read version from Directory.Build.props
+        id: read-version
+        run: |
+          version=$(grep -oP '<${{env.PROPS_VERSION_VAR_NAME}}>\K[^<]+' ./src/Directory.Build.props)
+          echo "PropsVersion=${version}" >> $GITHUB_ENV
+
+      - name: Compare tag with NuGet package version
+        run: |
+          if [ "${{ env.PropsVersion }}" != "${{ env.VERSION }}" ]; then
+            echo "Error: Tag does not match NuGet package version"
+            exit 1
+          fi
+          
+      - name: Read version from Info.plist
+        id: read-info-version
+        run: |
+          version=$(defaults read "$APP_NAME/Contents/Info.plist" CFBundleShortVersionString)
+          echo "InfoPlistVersion=${version}" >> $GITHUB_ENV
+
+      - name: Compare Info.plist version with environment variable
+        run: |
+          if [ "${{ env.InfoPlistVersion }}" != "${{ env.VERSION }}" ]; then
+            echo "Error: Info.plist version does not match the environment variable version"
+            exit 1
+          fi
 
       - name: Publish project
         run: dotnet publish -c Release -r osx-arm64 ./src/${{ env.PROJECT_NAME_DESKTOP }}/${{ env.PROJECT_NAME_DESKTOP }}.csproj -p:UseAppHost=true --self-contained -o ./publish/app
